# 1 Convert list to array

In [42]:
li=np.array([1,2,3,4,5])
print(li)

[1 2 3 4 5]


# 2 initialise 2-d array with 0

In [98]:
li0=np.zeros((3,3))
print(li0)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# 3 initialise 2-d array with 1

In [99]:
li1=np.ones((3,3))
print(li1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# 4 initialise array from 1 to 10

In [87]:
li4=np.arange(1,11)
print(li4)

[ 1  2  3  4  5  6  7  8  9 10]


# 5 concatinate two 2d array horizontally

In [135]:
mat1=np.array([[1,2,2],[1,2,3]])
mat2=np.array([[1,5,1],[2,2,5]])

#for vertical
#print(np.concatenate((mat1,mat2),axis=0))

#for horizontal
print(np.hstack((mat1,mat2)))

[[1 2 2 1 5 1]
 [1 2 3 2 2 5]]


# 6 reverse a list and find its size

In [54]:
li=np.array([1,2,3,4,5])
print(li[::-1])
print(li.size)

[5 4 3 2 1]
5


# 7 find matrix multiplication

In [57]:
mat1=np.array([[1,2],[1,2]])
mat2=np.array([[1,1],[2,2]])
res=np.matmul(mat1,mat2)
print(res)

[[5 5]
 [5 5]]


# 8 find mean median and standard deviation 

In [65]:
li=np.array([1,2,3,4,5,6,7,8])
print(np.mean(li))
print(np.median(li))
print(np.std(li))

4.5
4.5
2.29128784747792


# 9 initilise array with random values

In [96]:
li=np.random.randint(1,100,20)
print(li)

[80 60 33 69 98 82 37  9 93 85 47 69 19 67 11 82 51 72 42 43]


# 10 create 50 evenly spaced number from 1 to 10

In [116]:
li=np.linspace(1,10,50)
print(li)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


# 11 create 5x5 matrix with standard normal distribition

In [111]:
#num=np.random.randn(5,5)
num=np.random.standard_normal((5,5))
print(num)

[[-0.43066697  0.27258394  0.31808023 -0.77536624  1.12483076]
 [-0.11538172  0.89637821 -1.11344521 -0.00983982  1.58117052]
 [ 1.43308878  0.7948927  -0.46593559  1.25004544 -0.47539709]
 [-0.64147777  0.61850052  1.73833763  1.321805   -1.49322306]
 [-1.81188311 -0.70224227 -1.11848171  0.30448789  0.61255081]]


# 12 create array with all even numbers from 2 to 20

In [126]:
#21 because of inclusive range
num=np.arange(2,21,2)
print(num)

[ 2  4  6  8 10 12 14 16 18 20]


# 13 perform element-wise multiplication

In [127]:
mat1=np.array([[1,2],[1,2]])
mat2=np.array([[1,1],[2,2]])
print(mat1*mat2)

[[1 2]
 [2 4]]


# 14 reshape array to 2*3 matrix

In [129]:
li=np.array([1,2,3,4,5,6])
res=li.reshape(2,3)
print(res)

[[1 2 3]
 [4 5 6]]


# 15 find maximum and minimum in np array

In [130]:
li=np.random.randint(1,100,10)
print(li)
print(li.max())
print(li.min())

[12 49 67 52 18 85 98 51 40 14]
98
12


# 16 transpose a matrix

In [134]:
mat=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(mat.transpose())
#print(mat.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# 17 print elements greater than 5

In [136]:
li=np.random.randint(1,100,10)
print(li[li>5])

[97 87 36 76 25 78 45 27 11 30]


# 18 print even numbers

In [138]:
li=np.random.randint(1,100,10)
print(li[li%2==0])

[36 48  8 92 32]


# 19 Create 2d array 3*4 with random float from 0,1

In [146]:
arr=np.random.rand(3,4)
print(arr)

[[0.32728947 0.36806464 0.60816605 0.03396295]
 [0.96823167 0.97916856 0.84581047 0.08162111]
 [0.53807245 0.47081823 0.70082663 0.20093618]]


# 20 create a slice(0 to 5 index) of a given array and set value to 100 to the slice

In [150]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr[:5]=100
print(arr)

[100 100 100 100 100   6   7   8   9]


# 21 slice the first two rows and last two columns of 2d numpy array(right top corner)

In [156]:
mat=np.array([[1,2,3,4,5,7],[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(mat[:2,-2:])

[[5 7]
 [5 6]]
